export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';
export const GET_MENU_START = 'GET_MENU_START';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_NUMBER = 'GET_CART_NUMBER';
export const POST_ORDER_START = 'POST_ORDER_START ';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS ';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS';
export const GET_USER_ORDER_FAILURE = 'GET_USER_ORDER_FAILURE';
export const GET_USER_ORDER_START = 'GET_USER_ORDER_START';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';


